const youtubers = [
    {
        name: 'HandofBlood',
        reactions: ['took his punishment wheel with him', 'lost his mustache out of shock', 'lost his mustache out of enjoyment', 'says "War enttäuschend, bin ich early"', 'is lost in space digga'],
        pronoun: 'He'
    },
    {
        name: 'Pietsmiet',
        reactions: ['sticks his tongue out', 'takes a sip from his beer', 'screams agressively'],
        pronoun: 'He'
    },
    {
        name: 'Mahluna',
        reactions: ['laughs nervously', 'laughs awkwardly', 'laughs excited', 'smiles desperately'],
        pronoun: 'She'
    }
];

const actions = ['meets an excited Viewer in public','wins the "Deutscher Computerspielpreis"', 'gets a passenger ride in a race car', 'loses the last round in Valorant'];

// returns a random whole number from 0 to the passed number. The passed number should be generated with the length property of an array since the returned value will be used as 
// an Index for that Array to randomly select one Element.
function randomNum(arraylength) {
    return Math.floor(Math.random()*arraylength);
};

// numYoutuber should be passed with randomNum(youtubers.length) because its used to select a random element from the youtubers array.
// returns a sentence generated by adding the 4 template literals
// 1. The name of a youtuber, randomly selected by a random number.
// 2. Random element of the actions array chosen by generating a random number as an index with randomNum.
// 3. The Youtubers pronoun by using the same random number as an index as in the first literal.
// 4. Generating a randomNumber with the length of the reaction array of the chosen youtuber and using that number as an index for the reaction array of the chosen youtuber
function generateSentence(numYoutuber) {
    return `${youtubers[numYoutuber].name} ${actions[randomNum(actions.length)]}. ${youtubers[numYoutuber].pronoun} ${youtubers[numYoutuber].reactions[randomNum(youtubers[numYoutuber].reactions.length)]}!`;
}

//calling the method and printing the returned value, the sentence, to the console 
console.log(generateSentence(randomNum(youtubers.length)));

let button = document.querySelector('button');
button.onclick = ()=>{
    document.querySelector('h3').innerText = generateSentence(randomNum(youtubers.length));
};
